CREATE DATABASE DB_PT;
GO

USE DB_PT;
GO

CREATE TABLE CARGO
(
	IdCargo INT IDENTITY(1,1) NOT NULL
	,Descripcion VARCHAR(30) NOT NULL
	,FYHCreacion DATETIME NOT NULL
	,EstadoRegistro bit DEFAULT 1 --0 NO ACTIVO, 1 ACTIVO
	,RegistroEliminado bit DEFAULT 0 --0 NO ELIMINADO, 1 ELIMINADO
	CONSTRAINT PK_CARGO PRIMARY KEY (IdCargo)
)
GO
CREATE UNIQUE NONCLUSTERED INDEX IDX_CARGODESCRIPCION ON CARGO (Descripcion)
	WHERE RegistroEliminado=0;
GO
CREATE TABLE PERSONAL
(
	IdPersonal INT IDENTITY(1,1) NOT NULL
	,Nombres VARCHAR(30) NOT NULL
	,Apellidos VARCHAR(30) NOT NULL
	,Dni VARCHAR(10) NOT NULL
	,FechaNacimiento DATE NOT NULL
	,IdCargo INT NOT NULL
	,FYHCreacion DATETIME NOT NULL
	,EstadoRegistro bit DEFAULT 1 --0 NO ACTIVO, 1 ACTIVO
	,RegistroEliminado bit DEFAULT 0 --0 NO ELIMINADO, 1 ELIMINADO
	,CONSTRAINT PK_PERSONAL PRIMARY KEY (Idpersonal)
	,CONSTRAINT FK_PERSONAL_CARGO FOREIGN KEY (IdCargo) REFERENCES CARGO(IdCargo)
);
GO
CREATE UNIQUE NONCLUSTERED INDEX IDX_PERSONALDNI ON PERSONAL (Dni)
	WHERE RegistroEliminado=0;
CREATE UNIQUE NONCLUSTERED INDEX IDX_PERSONAL_NOMBRESAPELLIDOS ON PERSONAL (Nombres,Apellidos)
	WHERE RegistroEliminado=0;
GO
